### ISSUE TITLE
I try to use Drillable Tree KPI but it doesn't work. I'm using Lumira1.30

### ISSUE THREAD

**Issue by sunhanut** [SAP/lumira-extension-viz#21]
Hi All,
I would like to use this Drillable Tree KPI chart for my work but when i applied to my data, chart does   not display.  What should consider? My data or else, that cause i use my data with other chart that's fine.
Previously i downloaded data from this example and make chart, it works.
How going next step.

**Comment by sunhanut** [comment]
Guys,
Any limitation of data to use this Drillable Tree?

**Comment by AnnieMT** [comment]
Hi i @sunhanut 

This chart was designed specifically for the structure of data in the given sample. Please use your data in that manner for the chart to work. This is because the measures and dimensions work in the way they were built for this specific chart. Please use the data accordingly. Make sure you check your data types as well.
